import { ArrowDown, ArrowRight, Calculator, FileText, Landmark, MapPinned, Sparkles, TrendingUp, UserRound } from 'lucide-react'
import { Badge } from '../ui/Badge'
import { ButtonLink } from '../ui/Button'
const journey = [
  { icon: UserRound, title: 'Your Profile', detail: 'Location, Skills & Capital' }, { icon: MapPinned, title: 'Local Market', detail: 'Demand & Competition' },
  { icon: TrendingUp, title: 'Business Opportunities', detail: 'Explainable Matching' }, { icon: Calculator, title: 'Financial Planning', detail: 'Cost, Profit & Risk' },
  { icon: Landmark, title: 'Scheme Guidance', detail: 'Eligibility & Documents' }, { icon: FileText, title: 'Final Business Report', detail: 'Actionable Next Steps' },
]
export function LandingHero() { return <section className="landing-hero"><div className="container landing-hero__grid"><div className="landing-hero__copy"><Badge tone="orange"><Sparkles size={14} aria-hidden="true" /> Smart Rural Entrepreneurship Decision Support</Badge><h1>Turn Local Opportunities Into <span>Successful Businesses</span></h1><p>UdyamMitra helps aspiring and existing rural entrepreneurs understand local markets, evaluate business opportunities, plan finances, explore relevant schemes, and make better-informed business decisions.</p><div className="hero-actions"><ButtonLink to="/register">Start Business Analysis <ArrowRight size={18} aria-hidden="true" /></ButtonLink><a className="button button--outline" href="#how-it-works">See How It Works</a></div><small className="prototype-note">Decision-support prototype · Results require verification</small></div><div className="journey-preview" aria-label="Your Business Decision Journey"><header><span><TrendingUp aria-hidden="true" /></span><div><small>Guided decision support</small><h2>Your Business Decision Journey</h2></div></header><ol>{journey.map(({ icon: Icon, title, detail }, index) => <li key={title}><span className="journey-preview__icon"><Icon aria-hidden="true" /></span><div><small>Step {index + 1}</small><strong>{title}</strong><p>{detail}</p></div>{index < journey.length - 1 && <ArrowDown className="journey-preview__arrow" aria-hidden="true" />}</li>)}</ol><footer>Built around the information you choose to provide</footer></div></div></section> }
