import { useUi as useTextUi } from '../../i18n/uiContextValue'
import { LocalizedText } from '../../i18n/LocalizedText'
import { ArrowRight, BadgeCheck, BarChart3, Check, ChevronRight, CircleDollarSign, FileText, Landmark, MapPinned, RefreshCcw, ShieldCheck, Store, TrendingUp } from 'lucide-react'
import { capabilities, coreFeatures, demoOpportunities, financialChecks, financialMetrics, journeySteps, principles, problems, reportItems, stateLabels } from '../../data/landingData'
import { ButtonLink } from '../ui/Button'
import { Card } from '../ui/Card'
import { SectionHeading } from '../ui/Navigation'

export function TrustStrip() {
  const { text: textUi } = useTextUi()
 return <section className="capability-strip" aria-label={textUi("Platform capabilities")}><div className="container">{capabilities.map(({ icon: Icon, title }) => <div key={title}><Icon aria-hidden="true" /><span><LocalizedText value={title} /></span></div>)}</div></section> }

export function ProblemSection() {
  const { text: textUi } = useTextUi()
 return <section className="section"><div className="container"><SectionHeading eyebrow={textUi("The challenge")} title={textUi("Starting a Business Should Not Depend on Guesswork")} description={textUi("Good enterprise decisions need local evidence, realistic numbers and clear guidance—not assumptions.")} centered /><div className="problem-grid">{problems.map(({ icon: Icon, title, text }, i) => <Card className="problem-card" key={title}><span>0{i + 1}</span><Icon aria-hidden="true" /><h3><LocalizedText value={title} /></h3><p><LocalizedText value={text} /></p></Card>)}</div></div></section> }

export function HowItWorksSection() {
  const { text: textUi } = useTextUi()
 return <section className="section section--tinted" id="how-it-works"><div className="container"><SectionHeading eyebrow={textUi("A guided journey")} title={textUi("From Idea to Action — One Guided Journey")} description={textUi("Move through each decision in a clear sequence, while keeping the reasons and next steps visible.")} centered /><ol className="journey-grid">{journeySteps.map(step => <li key={step.n}><span className="journey-number">{step.n}</span><div><h3><LocalizedText value={step.title} /></h3><p><LocalizedText value={step.text} /></p></div></li>)}</ol></div></section> }

export function FeaturesSection() {
  const { text: textUi } = useTextUi()
 return <section className="section"><div className="container"><SectionHeading eyebrow={textUi("Complete decision support")} title={textUi("Everything You Need to Evaluate a Business Opportunity")} description={textUi("A connected toolkit for new ideas and existing enterprises—from local market context to a final report.")} centered /><div className="core-feature-grid">{coreFeatures.map(({ icon: Icon, title, text }, i) => <Card className="feature-card" key={title}><span className={`feature-icon feature-icon--${i % 3}`}><Icon aria-hidden="true" /></span><h3><LocalizedText value={title} /></h3><p><LocalizedText value={text} /></p></Card>)}</div></div></section> }

function OpportunityCard({ opportunity, index }: { opportunity: (typeof demoOpportunities)[number]; index: number }) { return <Card className="demo-opportunity"><div className="demo-opportunity__top"><span className="business-icon"><Store aria-hidden="true" /></span><span className="score-badge">{opportunity.score}<small>/100</small></span></div><small><LocalizedText value={"Demonstration opportunity "} />{String(index + 1).padStart(2, '0')}</small><h3><LocalizedText value={opportunity.title} /></h3><div className="capital-row"><span><LocalizedText value={"Estimated Capital"} /></span><strong>{opportunity.capital}</strong></div><div className="market-tags"><span><LocalizedText value={"Demand "} /><strong><LocalizedText value={opportunity.demand} /></strong></span><span><LocalizedText value={"Competition "} /><strong><LocalizedText value={opportunity.competition} /></strong></span></div></Card> }
export function OpportunitiesSection() {
  const { text: textUi } = useTextUi()
 return <section className="section opportunities-section"><div className="container"><div className="split-heading"><SectionHeading eyebrow={textUi("Illustrative demonstration data")} title={textUi("Explore Potential Rural Business Opportunities")} description={textUi("These examples show how opportunities may be presented. They are not live market results or recommendations.")} /><ButtonLink to="/register"><LocalizedText value={"Find Opportunities for My Area "} /><ArrowRight size={17} aria-hidden="true" /></ButtonLink></div><div className="opportunity-grid">{demoOpportunities.map((opportunity, i) => <OpportunityCard key={opportunity.title} opportunity={opportunity} index={i} />)}</div></div></section> }

export function AdvisorySection() {
  const { text: textUi } = useTextUi()
 return <section className="section section--tinted"><div className="container advisory-grid"><div><SectionHeading eyebrow={textUi("Existing business support")} title={textUi("Already Running a Business?")} description={textUi("UdyamMitra can also help existing entrepreneurs understand the health and future potential of their current business.")} /><div className="state-pills">{stateLabels.map(label => <span key={label}><LocalizedText value={label} /></span>)}</div><p><LocalizedText value={"Future recommendations will be based on user-entered financial information and local market analysis."} /></p><ButtonLink to="/register"><LocalizedText value={"Analyse My Existing Business "} /><ArrowRight size={17} aria-hidden="true" /></ButtonLink></div><Card className="health-card"><div className="demo-ribbon"><LocalizedText value={"Demonstration Analysis"} /></div><div className="health-title"><Store aria-hidden="true" /><span><small><LocalizedText value={"Current Business"} /></small><strong><LocalizedText value={"Kirana / General Store"} /></strong></span></div><div className="health-score"><div><strong>58</strong><span>/ 100</span><small><LocalizedText value={"Business Health"} /></small></div><div className="health-bars" aria-hidden="true"><i /><i /><i /><i /><i /></div></div><div className="health-details"><span><small><LocalizedText value={"Market Competition"} /></small><strong><LocalizedText value={"High"} /></strong></span><span><small><LocalizedText value={"Growth Potential"} /></small><strong><LocalizedText value={"Moderate"} /></strong></span></div><div className="recommendation"><RefreshCcw aria-hidden="true" /><span><small><LocalizedText value={"Illustrative Recommendation"} /></small><strong><LocalizedText value={"Improve / Diversify"} /></strong></span></div></Card></div></section> }

export function FinancialSection() {
  const { text: textUi } = useTextUi()
 return <section className="section financial-section"><div className="container financial-grid"><div><SectionHeading eyebrow={textUi("Plan before you commit")} title={textUi("Understand the Numbers Before You Invest")} description={textUi("Build a realistic view of funding, monthly operations and financial resilience before making an investment decision.")} /><ul className="check-list">{financialChecks.map(item => <li key={item}><Check aria-hidden="true" /><LocalizedText value={item} /></li>)}</ul></div><Card className="finance-preview"><div className="preview-label"><CircleDollarSign aria-hidden="true" /><span><LocalizedText value={"Financial Plan Preview"} /></span><small><LocalizedText value={"Demonstration data"} /></small></div><div className="finance-metrics">{financialMetrics.map(([label, value], i) => <div className={i > 3 ? 'highlight' : ''} key={label}><small><LocalizedText value={label} /></small><strong><LocalizedText value={value} /></strong></div>)}</div><p><LocalizedText value={"Figures are illustrative and do not represent financial advice."} /></p></Card></div></section> }

export function SchemesSection() {
  const { text: textUi } = useTextUi()
 return <section className="section section--tinted"><div className="container scheme-grid"><Card className="scheme-card"><div className="demo-ribbon"><LocalizedText value={"Sample guidance format"} /></div><Landmark className="scheme-icon" aria-hidden="true" /><small><LocalizedText value={"Potential Scheme Match"} /></small><h3><LocalizedText value={"Enterprise Support Programme"} /></h3><p><LocalizedText value={"Eligibility details will be evaluated against verified scheme rules."} /></p><div className="scheme-status"><BadgeCheck aria-hidden="true" /><LocalizedText value={" Potential match — verification required"} /></div><a href="/schemes"><LocalizedText value={"Review requirements "} /><ChevronRight size={16} aria-hidden="true" /></a></Card><div><SectionHeading eyebrow={textUi("Transparent scheme routing")} title={textUi("Find Relevant Support Schemes More Easily")} description={textUi("The future system will compare verified scheme rules with your business profile, without presenting an unverified benefit as guaranteed.")} /><ul className="scheme-inputs"><li><LocalizedText value={"Business type"} /></li><li><LocalizedText value={"Project cost"} /></li><li><LocalizedText value={"Location"} /></li><li><LocalizedText value={"Own contribution"} /></li><li><LocalizedText value={"Financing requirement"} /></li><li><LocalizedText value={"Eligibility rules"} /></li></ul><div className="scheme-disclaimer"><ShieldCheck aria-hidden="true" /><p><LocalizedText value={"Government scheme rules and eligibility criteria may change. Users should verify the latest guidelines from the respective official authority before applying."} /></p></div><ButtonLink to="/schemes" variant="outline"><LocalizedText value={"Explore Scheme Assistance"} /></ButtonLink></div></div></section> }

export function ReportSection() {
  const { text: textUi } = useTextUi()
 return <section className="section"><div className="container report-grid"><div><SectionHeading eyebrow={textUi("Bring every decision together")} title={textUi("One Consolidated Business Feasibility Report")} description={textUi("Review the complete reasoning behind an opportunity, its financial structure, risks, requirements and suggested next steps.")} /><p><LocalizedText value={"The report preview shows the planned structure only. Actual report generation will be implemented in a later module."} /></p><ButtonLink to="/reports/sample" variant="outline"><LocalizedText value={"See What the Report Includes "} /><ArrowRight size={17} aria-hidden="true" /></ButtonLink></div><div className="report-sheet"><header><span><FileText aria-hidden="true" /></span><div><small><LocalizedText value={"UdyamMitra"} /></small><strong><LocalizedText value={"Business Feasibility Report"} /></strong></div><em><LocalizedText value={"PREVIEW"} /></em></header><div className="report-business"><small><LocalizedText value={"Illustrative enterprise"} /></small><strong><LocalizedText value={"Mobile Repair & Accessories"} /></strong></div><ul>{reportItems.map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, '0')}</span><LocalizedText value={item} /><Check aria-hidden="true" /></li>)}</ul></div></div></section> }

export function WhySection() {
  const { text: textUi } = useTextUi()
 const icons = [BarChart3, MapPinned, TrendingUp, ShieldCheck]; return <section className="section why-section"><div className="container"><SectionHeading eyebrow={textUi("Our design principles")} title={textUi("Why UdyamMitra?")} description={textUi("Decision support should be understandable, grounded and responsible.")} centered /><div className="principle-grid">{principles.map(([title, text], i) => { const Icon = icons[i]; return <div key={title}><Icon aria-hidden="true" /><h3><LocalizedText value={title} /></h3><p><LocalizedText value={text} /></p></div> })}</div></div></section> }

export function FinalCtaSection() { return <section className="final-cta"><div className="container"><div><span className="eyebrow"><LocalizedText value={"Start with better context"} /></span><h2><LocalizedText value={"Make Your Next Business Decision With Better Information"} /></h2><p><LocalizedText value={"Create your profile and begin building a location-aware business feasibility analysis."} /></p></div><div><ButtonLink to="/register" variant="secondary"><LocalizedText value={"Get Started "} /><ArrowRight size={17} aria-hidden="true" /></ButtonLink><ButtonLink to="/login" variant="ghost"><LocalizedText value={"Login"} /></ButtonLink></div></div></section> }
