import { ArrowRight, BadgeCheck, BarChart3, Check, ChevronRight, CircleDollarSign, FileText, Landmark, MapPinned, RefreshCcw, ShieldCheck, Store, TrendingUp } from 'lucide-react'
import { capabilities, coreFeatures, demoOpportunities, financialChecks, financialMetrics, journeySteps, principles, problems, reportItems, stateLabels } from '../../data/landingData'
import { ButtonLink } from '../ui/Button'
import { Card } from '../ui/Card'
import { SectionHeading } from '../ui/Navigation'

export function TrustStrip() { return <section className="capability-strip" aria-label="Platform capabilities"><div className="container">{capabilities.map(({ icon: Icon, title }) => <div key={title}><Icon aria-hidden="true" /><span>{title}</span></div>)}</div></section> }

export function ProblemSection() { return <section className="section"><div className="container"><SectionHeading eyebrow="The challenge" title="Starting a Business Should Not Depend on Guesswork" description="Good enterprise decisions need local evidence, realistic numbers and clear guidance—not assumptions." centered /><div className="problem-grid">{problems.map(({ icon: Icon, title, text }, i) => <Card className="problem-card" key={title}><span>0{i + 1}</span><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></Card>)}</div></div></section> }

export function HowItWorksSection() { return <section className="section section--tinted" id="how-it-works"><div className="container"><SectionHeading eyebrow="A guided journey" title="From Idea to Action — One Guided Journey" description="Move through each decision in a clear sequence, while keeping the reasons and next steps visible." centered /><ol className="journey-grid">{journeySteps.map(step => <li key={step.n}><span className="journey-number">{step.n}</span><div><h3>{step.title}</h3><p>{step.text}</p></div></li>)}</ol></div></section> }

export function FeaturesSection() { return <section className="section"><div className="container"><SectionHeading eyebrow="Complete decision support" title="Everything You Need to Evaluate a Business Opportunity" description="A connected toolkit for new ideas and existing enterprises—from local market context to a final report." centered /><div className="core-feature-grid">{coreFeatures.map(({ icon: Icon, title, text }, i) => <Card className="feature-card" key={title}><span className={`feature-icon feature-icon--${i % 3}`}><Icon aria-hidden="true" /></span><h3>{title}</h3><p>{text}</p></Card>)}</div></div></section> }

function OpportunityCard({ opportunity, index }: { opportunity: (typeof demoOpportunities)[number]; index: number }) { return <Card className="demo-opportunity"><div className="demo-opportunity__top"><span className="business-icon"><Store aria-hidden="true" /></span><span className="score-badge">{opportunity.score}<small>/100</small></span></div><small>Demonstration opportunity {String(index + 1).padStart(2, '0')}</small><h3>{opportunity.title}</h3><div className="capital-row"><span>Estimated Capital</span><strong>{opportunity.capital}</strong></div><div className="market-tags"><span>Demand <strong>{opportunity.demand}</strong></span><span>Competition <strong>{opportunity.competition}</strong></span></div></Card> }
export function OpportunitiesSection() { return <section className="section opportunities-section"><div className="container"><div className="split-heading"><SectionHeading eyebrow="Illustrative demonstration data" title="Explore Potential Rural Business Opportunities" description="These examples show how opportunities may be presented. They are not live market results or recommendations." /><ButtonLink to="/register">Find Opportunities for My Area <ArrowRight size={17} aria-hidden="true" /></ButtonLink></div><div className="opportunity-grid">{demoOpportunities.map((opportunity, i) => <OpportunityCard key={opportunity.title} opportunity={opportunity} index={i} />)}</div></div></section> }

export function AdvisorySection() { return <section className="section section--tinted"><div className="container advisory-grid"><div><SectionHeading eyebrow="Existing business support" title="Already Running a Business?" description="UdyamMitra can also help existing entrepreneurs understand the health and future potential of their current business." /><div className="state-pills">{stateLabels.map(label => <span key={label}>{label}</span>)}</div><p>Future recommendations will be based on user-entered financial information and local market analysis.</p><ButtonLink to="/register">Analyse My Existing Business <ArrowRight size={17} aria-hidden="true" /></ButtonLink></div><Card className="health-card"><div className="demo-ribbon">Demonstration Analysis</div><div className="health-title"><Store aria-hidden="true" /><span><small>Current Business</small><strong>Kirana / General Store</strong></span></div><div className="health-score"><div><strong>58</strong><span>/ 100</span><small>Business Health</small></div><div className="health-bars" aria-hidden="true"><i /><i /><i /><i /><i /></div></div><div className="health-details"><span><small>Market Competition</small><strong>High</strong></span><span><small>Growth Potential</small><strong>Moderate</strong></span></div><div className="recommendation"><RefreshCcw aria-hidden="true" /><span><small>Illustrative Recommendation</small><strong>Improve / Diversify</strong></span></div></Card></div></section> }

export function FinancialSection() { return <section className="section financial-section"><div className="container financial-grid"><div><SectionHeading eyebrow="Plan before you commit" title="Understand the Numbers Before You Invest" description="Build a realistic view of funding, monthly operations and financial resilience before making an investment decision." /><ul className="check-list">{financialChecks.map(item => <li key={item}><Check aria-hidden="true" />{item}</li>)}</ul></div><Card className="finance-preview"><div className="preview-label"><CircleDollarSign aria-hidden="true" /><span>Financial Plan Preview</span><small>Demonstration data</small></div><div className="finance-metrics">{financialMetrics.map(([label, value], i) => <div className={i > 3 ? 'highlight' : ''} key={label}><small>{label}</small><strong>{value}</strong></div>)}</div><p>Figures are illustrative and do not represent financial advice.</p></Card></div></section> }

export function SchemesSection() { return <section className="section section--tinted"><div className="container scheme-grid"><Card className="scheme-card"><div className="demo-ribbon">Sample guidance format</div><Landmark className="scheme-icon" aria-hidden="true" /><small>Potential Scheme Match</small><h3>Enterprise Support Programme</h3><p>Eligibility details will be evaluated against verified scheme rules.</p><div className="scheme-status"><BadgeCheck aria-hidden="true" /> Potential match — verification required</div><a href="/schemes">Review requirements <ChevronRight size={16} aria-hidden="true" /></a></Card><div><SectionHeading eyebrow="Transparent scheme routing" title="Find Relevant Support Schemes More Easily" description="The future system will compare verified scheme rules with your business profile, without presenting an unverified benefit as guaranteed." /><ul className="scheme-inputs"><li>Business type</li><li>Project cost</li><li>Location</li><li>Own contribution</li><li>Financing requirement</li><li>Eligibility rules</li></ul><div className="scheme-disclaimer"><ShieldCheck aria-hidden="true" /><p>Government scheme rules and eligibility criteria may change. Users should verify the latest guidelines from the respective official authority before applying.</p></div><ButtonLink to="/schemes" variant="outline">Explore Scheme Assistance</ButtonLink></div></div></section> }

export function ReportSection() { return <section className="section"><div className="container report-grid"><div><SectionHeading eyebrow="Bring every decision together" title="One Consolidated Business Feasibility Report" description="Review the complete reasoning behind an opportunity, its financial structure, risks, requirements and suggested next steps." /><p>The report preview shows the planned structure only. Actual report generation will be implemented in a later module.</p><ButtonLink to="/reports/sample" variant="outline">See What the Report Includes <ArrowRight size={17} aria-hidden="true" /></ButtonLink></div><div className="report-sheet"><header><span><FileText aria-hidden="true" /></span><div><small>UdyamMitra</small><strong>Business Feasibility Report</strong></div><em>PREVIEW</em></header><div className="report-business"><small>Illustrative enterprise</small><strong>Mobile Repair &amp; Accessories</strong></div><ul>{reportItems.map((item, i) => <li key={item}><span>{String(i + 1).padStart(2, '0')}</span>{item}<Check aria-hidden="true" /></li>)}</ul></div></div></section> }

export function WhySection() { const icons = [BarChart3, MapPinned, TrendingUp, ShieldCheck]; return <section className="section why-section"><div className="container"><SectionHeading eyebrow="Our design principles" title="Why UdyamMitra?" description="Decision support should be understandable, grounded and responsible." centered /><div className="principle-grid">{principles.map(([title, text], i) => { const Icon = icons[i]; return <div key={title}><Icon aria-hidden="true" /><h3>{title}</h3><p>{text}</p></div> })}</div></div></section> }

export function FinalCtaSection() { return <section className="final-cta"><div className="container"><div><span className="eyebrow">Start with better context</span><h2>Make Your Next Business Decision With Better Information</h2><p>Create your profile and begin building a location-aware business feasibility analysis.</p></div><div><ButtonLink to="/register" variant="secondary">Get Started <ArrowRight size={17} aria-hidden="true" /></ButtonLink><ButtonLink to="/login" variant="ghost">Login</ButtonLink></div></div></section> }
