import type { BusinessDetail, BusinessFilters, BusinessListItem } from '../types/business'
import { apiClient } from './apiClient'

type WireListItem = { id: string; slug: string; name: string; category: BusinessListItem['category']; business_type: BusinessListItem['businessType']; short_description: string; minimum_capital: string; maximum_capital: string; is_active: boolean }
type WireDetail = WireListItem & { detailed_description: string; estimated_setup_cost_min: string; estimated_setup_cost_max: string; working_capital_min: string; working_capital_max: string; required_skills: string[]; preferred_skills: string[]; required_resources: string[]; optional_resources: string[]; equipment: string[]; customer_segments: string[]; market_drivers: string[]; competition_factors: string[]; supply_chain_factors: string[]; major_risks: string[]; required_registrations: string[]; operating_requirements: string[] }
const fromList = (item: WireListItem): BusinessListItem => ({ id: item.id, slug: item.slug, name: item.name, category: item.category, businessType: item.business_type, shortDescription: item.short_description, minimumCapital: item.minimum_capital, maximumCapital: item.maximum_capital, isActive: item.is_active })
const fromDetail = (item: WireDetail): BusinessDetail => ({ ...fromList(item), detailedDescription: item.detailed_description, estimatedSetupCostMin: item.estimated_setup_cost_min, estimatedSetupCostMax: item.estimated_setup_cost_max, workingCapitalMin: item.working_capital_min, workingCapitalMax: item.working_capital_max, requiredSkills: item.required_skills, preferredSkills: item.preferred_skills, requiredResources: item.required_resources, optionalResources: item.optional_resources, equipment: item.equipment, customerSegments: item.customer_segments, marketDrivers: item.market_drivers, competitionFactors: item.competition_factors, supplyChainFactors: item.supply_chain_factors, majorRisks: item.major_risks, requiredRegistrations: item.required_registrations, operatingRequirements: item.operating_requirements })

export const businessService = {
  async list(filters: BusinessFilters = {}): Promise<BusinessListItem[]> { const params = { category: filters.category || undefined, business_type: filters.businessType || undefined, search: filters.search?.trim() || undefined }; return (await apiClient.get<WireListItem[]>('/businesses', { params })).data.map(fromList) },
  async get(identifier: string): Promise<BusinessDetail> { return fromDetail((await apiClient.get<WireDetail>(`/businesses/${encodeURIComponent(identifier)}`)).data) },
}
