import { AlertCircle, ArrowRight, BarChart3, BriefcaseBusiness, LoaderCircle, Search, SlidersHorizontal } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Button } from '../../components/ui/Button'
import { getApiErrorMessage } from '../../services/apiError'
import { businessService } from '../../services/businessService'
import { feasibilityService } from '../../services/feasibilityService'
import { marketService } from '../../services/marketService'
import type { BusinessCategory, BusinessFilters, BusinessListItem, BusinessType } from '../../types/business'
import type { FeasibilityAnalysis } from '../../types/feasibility'
import type { MarketAnalysis } from '../../types/market'
import { categoryLabels, moneyRange, typeLabels } from './businessFormatters'
import { FeasibilityDisclaimer, TopMatchCard } from './FeasibilityViews'

const categories: BusinessCategory[] = ['RETAIL', 'SERVICES', 'AGRICULTURE', 'FOOD_PROCESSING', 'MANUFACTURING']
const types: BusinessType[] = ['SERVICE', 'RETAIL', 'AGRI_ALLIED', 'PROCESSING', 'RENTAL']
const componentScore = (result: FeasibilityAnalysis['results'][number], code: string) => result.components.find(item => item.code === code)?.score ?? 0

export function BusinessCatalogPage() {
  const [search, setSearch] = useState(''); const [category, setCategory] = useState<BusinessCategory | ''>(''); const [businessType, setBusinessType] = useState<BusinessType | ''>(''); const [businesses, setBusinesses] = useState<BusinessListItem[]>([])
  const [market, setMarket] = useState<MarketAnalysis | null>(null); const [analysis, setAnalysis] = useState<FeasibilityAnalysis | null>(null); const [loading, setLoading] = useState(true); const [catalogLoading, setCatalogLoading] = useState(true); const [running, setRunning] = useState(false); const [error, setError] = useState(''); const [reload, setReload] = useState(0)
  const fetchBusinesses = useCallback((filters: BusinessFilters) => businessService.list(filters).then(setBusinesses).catch(reason => setError(getApiErrorMessage(reason, 'Unable to load the business catalog.'))).finally(() => setCatalogLoading(false)), [])
  useEffect(() => { void Promise.all([marketService.latest(), feasibilityService.latest()]).then(([savedMarket, savedAnalysis]) => { setMarket(savedMarket); setAnalysis(savedAnalysis) }).catch(reason => setError(getApiErrorMessage(reason, 'Unable to load personalized opportunity analysis.'))).finally(() => setLoading(false)) }, [reload])
  useEffect(() => { const timer = window.setTimeout(() => { void fetchBusinesses({ search, category: category || undefined, businessType: businessType || undefined }) }, 250); return () => window.clearTimeout(timer) }, [businessType, category, fetchBusinesses, reload, search])
  const analyze = async () => { if (!market) return; setRunning(true); setError(''); try { setAnalysis(await feasibilityService.analyze(market.id)) } catch (reason) { setError(getApiErrorMessage(reason, 'Unable to generate feasibility analysis.')) } finally { setRunning(false) } }
  return <div className="catalog-page"><header className="catalog-heading"><span className="eyebrow">Personalized decision support</span><h1>Business Opportunities for Your Profile</h1><p>Compare supported business models using your profile and saved local market evidence.</p></header>
    {loading ? <section className="feasibility-state"><LoaderCircle className="spin" /><h2>Loading your opportunity workspace…</h2></section> : !market ? <section className="feasibility-state feasibility-state--required"><BarChart3 /><h2>Run Local Market Analysis First</h2><p>Personalized feasibility requires a persisted local market snapshot. No recommendation is generated without that evidence.</p><Link className="button button--success" to="/market-analysis">Run Market Analysis <ArrowRight /></Link></section> : !analysis ? <section className="feasibility-state"><BriefcaseBusiness /><h2>Market evidence is ready</h2><p>Generate an immutable analysis of all supported active business profiles using your skills, resources, capital information, and the saved market snapshot.</p><Button type="button" onClick={() => void analyze()} disabled={running}>{running ? <><LoaderCircle className="spin" /> Analysing opportunities…</> : 'Generate My Business Feasibility Analysis'}</Button></section> : <PersonalizedResults analysis={analysis} onAnalyze={analyze} running={running} />}
    {error && <div className="market-error-inline" role="alert"><AlertCircle /> {error} <button type="button" onClick={() => setReload(value => value + 1)}>Retry</button></div>}
    <section className="catalog-library" aria-labelledby="catalog-library-title"><div className="catalog-section-heading"><div><span className="eyebrow">Business knowledge library</span><h2 id="catalog-library-title">Explore All Business Profiles</h2></div></div><section className="catalog-filters" aria-label="Business catalog filters"><label><span>Search businesses</span><div><Search /><input type="search" value={search} onChange={event => { setCatalogLoading(true); setError(''); setSearch(event.target.value) }} placeholder="Search by name or activity" /></div></label><label><span>Category</span><select value={category} onChange={event => { setCatalogLoading(true); setCategory(event.target.value as BusinessCategory | '') }}><option value="">All categories</option>{categories.map(value => <option key={value} value={value}>{categoryLabels[value]}</option>)}</select></label><label><span>Business type</span><select value={businessType} onChange={event => { setCatalogLoading(true); setBusinessType(event.target.value as BusinessType | '') }}><option value="">All business types</option>{types.map(value => <option key={value} value={value}>{typeLabels[value]}</option>)}</select></label><span className="filter-summary"><SlidersHorizontal /> Catalog filters</span></section>
      {catalogLoading ? <CatalogSkeleton /> : businesses.length === 0 ? <section className="catalog-state"><BriefcaseBusiness /><h2>No business profiles available.</h2></section> : <><div className="catalog-result-count" aria-live="polite">{businesses.length} business {businesses.length === 1 ? 'profile' : 'profiles'}</div><section className="business-catalog-grid" aria-label="Business profiles">{businesses.map(business => <article className="business-catalog-card" key={business.id}><div className="business-card__top"><span><BriefcaseBusiness /></span><div><small>{categoryLabels[business.category]}</small><strong>{typeLabels[business.businessType]}</strong></div></div><h2>{business.name}</h2><p>{business.shortDescription}</p><dl><dt>Estimated capital range</dt><dd>{moneyRange(business.minimumCapital, business.maximumCapital)}</dd></dl><Link to={`/opportunities/${business.slug}`}>View Business <ArrowRight /></Link></article>)}</section></>}
    </section>
  </div>
}

function PersonalizedResults({ analysis, onAnalyze, running }: { analysis: FeasibilityAnalysis; onAnalyze: () => Promise<void>; running: boolean }) { return <div className="personalized-results"><div className="analysis-meta"><div><span className="eyebrow">Feasibility snapshot</span><h2>Top Feasibility Matches</h2><p>Generated {new Date(analysis.createdAt).toLocaleString('en-IN')} · {analysis.analysisVersion} · market {analysis.marketAnalysisVersion}</p></div><Button variant="outline" type="button" onClick={() => void onAnalyze()} disabled={running}>{running ? 'Analysing…' : 'Generate New Snapshot'}</Button></div><FeasibilityDisclaimer text={analysis.disclaimer} /><section className="top-match-grid" aria-label="Top three feasibility matches">{analysis.topMatches.map(result => <TopMatchCard key={result.businessId} result={result} />)}</section><section className="all-feasibility-results" aria-labelledby="all-results-title"><h2 id="all-results-title">All Business Results</h2><p>Ranked by feasibility score, then demand, skill match, and stable business name.</p><div className="feasibility-table-wrap"><table><thead><tr><th>Rank</th><th>Business</th><th>Score</th><th>Demand</th><th>Competition</th><th>Skills</th><th>Financial</th><th>Access</th><th>Supply</th><th>Details</th></tr></thead><tbody>{analysis.results.map(result => <tr key={result.businessId}><td>#{result.rank}</td><th scope="row">{result.businessName}{result.isCurrentBusiness && <small className="table-current">Your Current Business</small>}</th><td><strong>{result.finalFeasibilityScore}/100</strong><small>{result.feasibilityLabel.replaceAll('_', ' ')}</small></td>{(['LOCAL_DEMAND','COMPETITION_OPPORTUNITY','SKILL_MATCH','FINANCIAL_FIT','MARKET_ACCESS','SUPPLY_CHAIN'] as const).map(code => <td key={code}>{componentScore(result, code)}</td>)}<td><Link to={`/opportunities/${result.businessSlug}`}>View Breakdown</Link></td></tr>)}</tbody></table></div></section><section className="calculation-explainer"><h2>How Your Score Is Calculated</h2><p>The deterministic score uses 25% Local Demand, 20% Competition Opportunity, 20% Skill Match, 15% Financial Fit, 10% Market Access, and 10% Supply Chain. Market values come directly from the bound saved market-analysis snapshot.</p></section></div> }
function CatalogSkeleton() { return <div className="catalog-skeleton" aria-label="Loading business profiles" role="status">{Array.from({ length: 8 }, (_, index) => <i key={index} />)}<span className="sr-only">Loading business profiles…</span></div> }
