import { useUi as useTextUi } from '../../i18n/uiContextValue'
import { LocalizedText } from '../../i18n/LocalizedText'
import { AlertTriangle, ArrowLeft, ArrowRight, BriefcaseBusiness, CheckCircle2, IndianRupee, Info } from 'lucide-react'
import { useCallback, useEffect, useState } from 'react'
import { Link, useParams } from 'react-router-dom'
import { Button } from '../../components/ui/Button'
import { getApiErrorMessage } from '../../services/apiError'
import { businessService } from '../../services/businessService'
import { feasibilityService } from '../../services/feasibilityService'
import type { BusinessDetail } from '../../types/business'
import type { FeasibilityResult } from '../../types/feasibility'
import { categoryLabels, moneyRange, typeLabels } from './businessFormatters'
import { FeasibilityDisclaimer, ScoreBlock, ScoreBreakdown } from './FeasibilityViews'

const sections: Array<{ key: keyof BusinessDetail; title: string }> = [
  { key: 'requiredSkills', title: 'Required Skills' }, { key: 'preferredSkills', title: 'Preferred Skills' }, { key: 'requiredResources', title: 'Required Resources' }, { key: 'optionalResources', title: 'Optional Resources' }, { key: 'equipment', title: 'Equipment' }, { key: 'customerSegments', title: 'Customer Segments' }, { key: 'marketDrivers', title: 'Market Drivers' }, { key: 'competitionFactors', title: 'Competition Factors' }, { key: 'supplyChainFactors', title: 'Supply Chain Factors' }, { key: 'majorRisks', title: 'Major Risks' }, { key: 'operatingRequirements', title: 'Operating Requirements' },
]

export function BusinessDetailPage() {
  const { text: textUi } = useTextUi()

  const { businessId = '' } = useParams(); const [business, setBusiness] = useState<BusinessDetail | null>(null); const [feasibility, setFeasibility] = useState<FeasibilityResult | null>(null); const [disclaimer, setDisclaimer] = useState(''); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [reload, setReload] = useState(0)
  const load = useCallback(() => Promise.all([businessService.get(businessId), feasibilityService.latest()]).then(([savedBusiness, analysis]) => { setBusiness(savedBusiness); setFeasibility(analysis?.results.find(item => item.businessId === savedBusiness.id) ?? null); setDisclaimer(analysis?.disclaimer ?? '') }).catch(reason => setError(getApiErrorMessage(reason, 'This business profile could not be found.'))).finally(() => setLoading(false)), [businessId])
  useEffect(() => { void load() }, [load, reload])
  if (loading) return <div className="business-detail-page"><div className="detail-skeleton" role="status"><i /><i /><i /><span className="sr-only"><LocalizedText value={"Loading business profile…"} /></span></div></div>
  if (error || !business) return <div className="business-detail-page"><section className="catalog-state catalog-state--error" role="alert"><AlertTriangle aria-hidden="true" /><h1><LocalizedText value={"Business profile unavailable"} /></h1><p><LocalizedText value={error || 'This business profile could not be found.'} /></p><div><Button type="button" onClick={() => { setLoading(true); setError(''); setReload(value => value + 1) }}><LocalizedText value={"Retry"} /></Button><Link className="button button--outline" to="/opportunities"><LocalizedText value={"Back to Opportunities"} /></Link></div></section></div>
  return <div className="business-detail-page"><Link className="detail-back" to="/opportunities"><ArrowLeft aria-hidden="true" /><LocalizedText value={" Back to Opportunities"} /></Link><header className="business-detail-heading"><div><span className="eyebrow"><LocalizedText value={categoryLabels[business.category]} /> · <LocalizedText value={typeLabels[business.businessType]} /></span><h1>{business.name}</h1><p><LocalizedText value={business.shortDescription} /></p></div><span className="business-detail-icon"><BriefcaseBusiness aria-hidden="true" /></span></header>
    {feasibility && <PersonalizedDetail result={feasibility} disclaimer={disclaimer} />}
    <section className="business-overview-grid"><article className="business-overview"><h2><LocalizedText value={"Business Overview"} /></h2><p><LocalizedText value={business.detailedDescription} /></p><div className="estimate-note"><Info aria-hidden="true" /><LocalizedText value={" These are demonstration planning estimates, not guaranteed costs or returns."} /></div></article><article className="business-cost-card"><IndianRupee aria-hidden="true" /><h2><LocalizedText value={"Planning Cost Ranges"} /></h2><dl><div><dt><LocalizedText value={"Capital range"} /></dt><dd>{moneyRange(business.minimumCapital, business.maximumCapital)}</dd></div><div><dt><LocalizedText value={"Typical setup cost"} /></dt><dd>{moneyRange(business.estimatedSetupCostMin, business.estimatedSetupCostMax)}</dd></div><div><dt><LocalizedText value={"Working capital"} /></dt><dd>{moneyRange(business.workingCapitalMin, business.workingCapitalMax)}</dd></div></dl><div style={{ marginTop: '16px' }}><Link className="button button--outline" to={`/financial-plan/${business.slug}`}><LocalizedText value={"Plan Financing "} /><ArrowRight aria-hidden="true" /></Link></div></article></section>
    <section className="knowledge-grid" aria-label={textUi("Structured business knowledge")}>{sections.map(({ key, title }) => <KnowledgeSection key={key} title={textUi(title)} items={business[key] as string[]} risk={key === 'majorRisks'} />)}</section>
    <section className="compliance-card"><AlertTriangle aria-hidden="true" /><div><h2><LocalizedText value={"Potential registrations and compliance requirements may include"} /></h2><ul>{business.requiredRegistrations.map(item => <li key={item}><LocalizedText value={item} /></li>)}</ul><p><LocalizedText value={"Actual registration and licence requirements depend on business scale, location and applicable regulations. Verify current requirements from official authorities."} /></p></div></section>
    <section className="business-analysis-cta"><div><span className="eyebrow"><LocalizedText value={"Next step"} /></span><h2><LocalizedText value={feasibility ? 'Review All Opportunities' : 'Analyse This Business'} /></h2><p><LocalizedText value={feasibility ? 'Compare this result objectively with all other supported business profiles.' : 'Personalized feasibility requires a saved local market analysis and an explicit feasibility run.'} /></p></div><div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}><Link className="button button--success" to={feasibility ? '/opportunities' : '/market-analysis'}><LocalizedText value={feasibility ? 'View Ranked Opportunities' : 'Start Market Analysis'} /> <ArrowRight aria-hidden="true" /></Link><Link className="button button--secondary" to={`/financial-plan/${business.slug}`}><LocalizedText value={"Plan Financing "} /><ArrowRight aria-hidden="true" /></Link></div></section>
  </div>
}

function KnowledgeSection({ title, items, risk = false }: { title: string; items: string[]; risk?: boolean }) { return <article className={risk ? 'knowledge-card knowledge-card--risk' : 'knowledge-card'}><h2><LocalizedText value={title} /></h2>{items.length ? <ul>{items.map(item => <li key={item}><LocalizedText value={item} /></li>)}</ul> : <p><LocalizedText value={"No additional items listed."} /></p>}</article> }

function PersonalizedDetail({ result, disclaimer }: { result: FeasibilityResult; disclaimer: string }) { return <section className="personal-feasibility" aria-labelledby="personal-feasibility-title"><header><div><span className="eyebrow"><LocalizedText value={"Your saved profile and market evidence"} /></span><h2 id="personal-feasibility-title"><LocalizedText value={"Your Feasibility Analysis"} /></h2>{result.isCurrentBusiness && <span className="current-business-badge"><LocalizedText value={"Your Current Business"} /></span>}</div><ScoreBlock result={result} /></header><FeasibilityDisclaimer text={disclaimer} /><ScoreBreakdown result={result} /><div className="feasibility-evidence-grid"><article><h3><LocalizedText value={"Skills Match"} /></h3><p><strong>{result.skills.skillMatchScore}/100</strong></p><h4><LocalizedText value={"Matched required skills"} /></h4><List items={result.skills.matchedRequiredSkills} empty="No required skill matches recorded." /><h4><LocalizedText value={"Missing skills"} /></h4><List items={result.skills.missingRequiredSkills} empty="No required skills missing." /></article><article><h3><LocalizedText value={"Resource Readiness"} /></h3><p><strong>{result.resources.resourceReadinessScore}/100</strong></p><h4><LocalizedText value={"Available required resources"} /></h4><List items={result.resources.availableRequiredResources} empty="No required resource matches recorded." /><h4><LocalizedText value={"Missing resources"} /></h4><List items={result.resources.missingRequiredResources} empty="No required resources missing." /></article><article><h3><LocalizedText value={"Capital Fit"} /></h3><p><LocalizedText value={result.capitalFitExplanation} /></p>{result.financingMayBeRequired && <span className="caution-label"><LocalizedText value={"Financing may be required"} /></span>}<h3><LocalizedText value={"Strengths"} /></h3><List items={result.strengths.map(item => item.title)} empty="No component crossed the strong-evidence threshold." /></article><article><h3><LocalizedText value={"Gaps and Risks"} /></h3><List items={[...result.gaps.map(item => `${item.severity}: ${item.explanation}`), ...result.marketThreats.map(item => item.explanation)]} empty="No deterministic gap was triggered." /><h3><LocalizedText value={"Next Actions"} /></h3><List items={result.nextActions} empty="Validate assumptions with customers before investing." /></article></div></section> }
function List({ items, empty }: { items: string[]; empty: string }) { return items.length ? <ul>{items.map(item => <li key={item}><CheckCircle2 /><LocalizedText value={item} /></li>)}</ul> : <p><LocalizedText value={empty} /></p> }
