import { useUi as useTextUi } from '../../i18n/uiContextValue'
import { LocalizedText } from '../../i18n/LocalizedText'
import { AlertTriangle, ArrowRight, CheckCircle2, Gauge, ShieldCheck } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { FeasibilityResult } from '../../types/feasibility'

export function ScoreBlock({ result }: { result: FeasibilityResult }) {
  const { text: textUi } = useTextUi()
 return <div className={`feasibility-score feasibility-score--${result.feasibilityLabel.toLowerCase()}`} aria-label={textUi(`${result.finalFeasibilityScore} out of 100, ${result.feasibilityLabel.replaceAll('_', ' ')}`)}><strong>{result.finalFeasibilityScore}<small>/100</small></strong><span><LocalizedText value={result.feasibilityLabel.replaceAll('_', ' ')} /></span></div> }
export function TopMatchCard({ result }: { result: FeasibilityResult }) { return <article className="top-match-card"><header><span className="rank-badge"><LocalizedText value={"Rank "} />{result.rank}</span>{result.isCurrentBusiness && <span className="current-business-badge"><LocalizedText value={"Your Current Business"} /></span>}</header><div className="top-match-main"><div><small><LocalizedText value={result.businessCategory.replaceAll('_', ' ')} /></small><h3>{result.businessName}</h3></div><ScoreBlock result={result} /></div><p><LocalizedText value={result.shortDescription} /></p><div className="match-summary"><span><CheckCircle2 /> <LocalizedText value={result.strengths[0]?.title || 'Profile and market evidence assessed'} /></span>{result.gaps[0] && <span className="match-caution"><AlertTriangle /> <LocalizedText value={result.gaps[0].code.replaceAll('_', ' ')} /></span>}</div><Link to={`/opportunities/${result.businessSlug}`}><LocalizedText value={"View Feasibility "} /><ArrowRight /></Link></article> }
export function ScoreBreakdown({ result }: { result: FeasibilityResult }) { return <section className="score-breakdown" aria-labelledby="score-breakdown-title"><div className="feasibility-section-heading"><Gauge /><div><span className="eyebrow"><LocalizedText value={"Transparent calculation"} /></span><h2 id="score-breakdown-title"><LocalizedText value={"Score Breakdown"} /></h2></div></div><div className="component-grid">{result.components.map(item => <article key={item.code}><div><strong><LocalizedText value={item.title} /></strong><span>{Number(item.weight) * 100}<LocalizedText value={"% weight"} /></span></div><div className="score-progress"><i style={{ width: `${item.score}%` }} /><span className="sr-only">{item.score}<LocalizedText value={" out of 100"} /></span></div><dl><div><dt><LocalizedText value={"Raw score"} /></dt><dd>{item.score}/100</dd></div><div><dt><LocalizedText value={"Contribution"} /></dt><dd>{item.weightedContribution}</dd></div></dl></article>)}</div></section> }
export function FeasibilityDisclaimer({ text }: { text: string }) { return <div className="feasibility-disclaimer"><ShieldCheck aria-hidden="true" /><p><LocalizedText value={text} /></p></div> }
