import { zodResolver } from '@hookform/resolvers/zod'
import { Check, Circle } from 'lucide-react'
import { useState } from 'react'
import { useForm, useWatch } from 'react-hook-form'
import { Link, useNavigate } from 'react-router-dom'
import { AuthField, AuthSelect, PasswordField } from '../../components/auth/AuthFields'
import { AuthNotice } from '../../components/auth/AuthNotice'
import { Button } from '../../components/ui/Button'
import { registerSchema, type RegisterFormData } from '../../features/auth/authSchemas'
import { useAuth } from '../../context/authContextValue'
import { getApiErrorMessage } from '../../services/apiError'

const requirements = [{ label: '8+ characters', test: (v: string) => v.length >= 8 }, { label: 'Uppercase letter', test: (v: string) => /[A-Z]/.test(v) }, { label: 'Lowercase letter', test: (v: string) => /[a-z]/.test(v) }, { label: 'Number', test: (v: string) => /\d/.test(v) }]
export function RegisterPage() {
  const [submitted, setSubmitted] = useState(false)
  const [serverError, setServerError] = useState(''); const { register: createAccount } = useAuth(); const navigate = useNavigate()
  const { register, handleSubmit, control, formState: { errors, isSubmitting } } = useForm<RegisterFormData>({ resolver: zodResolver(registerSchema), defaultValues: { fullName: '', mobile: '', email: '', preferredLanguage: 'en', password: '', confirmPassword: '', termsAccepted: false } })
  const password = useWatch({ control, name: 'password' })
  const onSubmit = async (values: RegisterFormData) => { setSubmitted(false); setServerError(''); try { await createAccount(values); setSubmitted(true); navigate('/onboarding', { replace: true }) } catch (error) { setServerError(getApiErrorMessage(error, 'Unable to create your account. Please try again.')) } }
  return <section className="auth-card auth-card--register"><span className="eyebrow">Create your profile</span><h2>Create Your UdyamMitra Account</h2><p>Create an account to save your profile, business analyses and reports.</p><form onSubmit={handleSubmit(onSubmit)} noValidate><div className="form-grid"><AuthField id="register-name" label="Full Name" autoComplete="name" placeholder="Enter your full name" error={errors.fullName?.message} {...register('fullName')} /><AuthField id="register-mobile" label="Mobile Number" inputMode="numeric" autoComplete="tel" placeholder="10-digit mobile number" error={errors.mobile?.message} {...register('mobile')} /><AuthField id="register-email" label="Email Address" type="email" autoComplete="email" placeholder="Enter your email address" error={errors.email?.message} {...register('email')} /><AuthSelect id="register-language" label="Preferred Language" error={errors.preferredLanguage?.message} {...register('preferredLanguage')}><option value="en">English</option><option value="mr">मराठी</option><option value="hi">हिन्दी</option></AuthSelect></div><PasswordField id="register-password" label="Password" autoComplete="new-password" placeholder="Create a strong password" error={errors.password?.message} {...register('password')} /><div className="password-rules" aria-label="Password requirements" aria-live="polite"><span>Password must contain:</span><ul>{requirements.map(item => { const met = item.test(password ?? ''); return <li className={met ? 'met' : ''} key={item.label}>{met ? <Check aria-hidden="true" /> : <Circle aria-hidden="true" />}{item.label}</li> })}</ul></div><PasswordField id="register-confirm" label="Confirm Password" autoComplete="new-password" placeholder="Re-enter your password" error={errors.confirmPassword?.message} {...register('confirmPassword')} /><label className="choice terms-choice"><input type="checkbox" aria-invalid={Boolean(errors.termsAccepted)} aria-describedby={errors.termsAccepted ? 'terms-error' : undefined} {...register('termsAccepted')} /><span>I agree to the <Link to="/terms">Terms of Use</Link> and <Link to="/privacy">Privacy Policy</Link>.</span></label>{errors.termsAccepted && <span className="field-error" id="terms-error" role="alert">{errors.termsAccepted.message}</span>}{serverError && <p className="integration-message integration-message--error" role="alert">{serverError}</p>}{submitted && <p className="integration-message" role="status">Account created. Redirecting…</p>}<Button type="submit" disabled={isSubmitting}>{isSubmitting ? 'Creating account…' : 'Create Account'}</Button></form><AuthNotice /><p className="auth-link">Already have an account? <Link to="/login">Login</Link></p></section>
}
