import { ArrowRight, BarChart3, BriefcaseBusiness, Building2, FileClock, HeartPulse, MapPin } from 'lucide-react'
import { Link } from 'react-router-dom'
import type { EntrepreneurProfile } from '../../types/profile'
import type { FeasibilityAnalysis } from '../../types/feasibility'
import { formatCurrency } from './dashboardFormatters'

export function PrimaryJourney({ profile }: { profile: EntrepreneurProfile }) {
  const existing = profile.hasExistingBusiness === true
  return <section className="primary-journey" aria-labelledby="primary-journey-title"><div><span className="eyebrow">Recommended next action</span><h2 id="primary-journey-title">Start Your Business Analysis</h2><p>{existing ? 'Review your current business using the details already saved in your profile.' : 'Begin with your location so future recommendations can be based on local evidence.'}</p></div><div className="primary-journey__actions"><Link className="button button--success" to={existing ? '/business-health' : '/market-analysis'}>{existing ? 'Analyse My Existing Business' : 'Analyse My Area'} <ArrowRight aria-hidden="true" /></Link><Link className="button button--secondary" to="/opportunities">{existing ? 'Explore Better Opportunities' : 'Explore Business Opportunities'}</Link></div></section>
}

export function CurrentBusinessCard({ profile }: { profile: EntrepreneurProfile }) {
  const business = profile.existingBusiness
  if (!profile.hasExistingBusiness || !business) return <section className="dashboard-card current-business-card" aria-labelledby="business-card-title"><span className="panel-icon"><BriefcaseBusiness aria-hidden="true" /></span><div><h2 id="business-card-title">Looking for a New Business?</h2><p>Use your profile and local market information to discover suitable opportunities.</p><Link to="/opportunities">Find Opportunities <ArrowRight aria-hidden="true" /></Link></div></section>
  return <section className="dashboard-card current-business-card current-business-card--existing" aria-labelledby="business-card-title"><span className="panel-icon"><HeartPulse aria-hidden="true" /></span><div><h2 id="business-card-title">Your Current Business</h2><h3>{business.businessName}</h3><dl><div><dt>Category</dt><dd>{business.businessCategory}</dd></div><div><dt>Years operating</dt><dd>{business.yearsOperating}</dd></div><div><dt>Monthly revenue</dt><dd>{formatCurrency(business.monthlyRevenue)}</dd></div><div><dt>Monthly expenses</dt><dd>{formatCurrency(business.monthlyExpenses)}</dd></div></dl><Link to="/business-health">Analyse Business Health <ArrowRight aria-hidden="true" /></Link></div></section>
}

const analysisCards = [
  { title: 'Business Opportunities', text: 'No personalised opportunities generated yet.', detail: 'Once local market analysis is available, UdyamMitra will combine your skills, capital, resources and market evidence to rank suitable businesses.', action: 'Explore Analysis', to: '/opportunities', icon: BarChart3 },
  { title: 'Government Scheme Guidance', text: 'Scheme matching will become available after your business and financing requirements are defined.', detail: 'Always verify scheme details and eligibility using official government sources before applying.', action: 'Explore Schemes', to: '/schemes', icon: Building2 },
]
export function AnalysisEmptyStates({ marketAnalysisDate, feasibility }: { marketAnalysisDate?: string; feasibility?: FeasibilityAnalysis | null }) { const marketCard = { title: 'Local Market Intelligence', text: marketAnalysisDate ? 'Market Analysis Available' : 'Your market analysis has not been generated yet.', detail: marketAnalysisDate ? `Latest curated demonstration analysis: ${new Date(marketAnalysisDate).toLocaleDateString('en-IN')}.` : 'Analyse nearby demonstration businesses, demand indicators, competition and market access.', action: marketAnalysisDate ? 'View or Run Again' : 'Start Market Analysis', to: '/market-analysis', icon: MapPin }; const opportunityCard = feasibility ? { title: 'Business Opportunities', text: 'Business Feasibility Available', detail: `${feasibility.topMatches[0]?.businessName || 'Top match'} · ${feasibility.topMatches[0]?.finalFeasibilityScore ?? 0}/100 · generated ${new Date(feasibility.createdAt).toLocaleDateString('en-IN')}.`, action: 'View Opportunities', to: '/opportunities', icon: BarChart3 } : analysisCards[0]; return <section className="dashboard-section" aria-labelledby="analysis-title"><div className="dashboard-section__heading"><div><span className="eyebrow">Analysis workspace</span><h2 id="analysis-title">Build your evidence base</h2></div></div><div className="analysis-empty-grid">{[marketCard, opportunityCard, analysisCards[1]].map(({ title, text, detail, action, to, icon: Icon }) => <article className="dashboard-card analysis-empty-card" key={title}><span className="panel-icon"><Icon aria-hidden="true" /></span><h3>{title}</h3><strong>{text}</strong><p>{detail}</p><Link to={to}>{action} <ArrowRight aria-hidden="true" /></Link></article>)}</div></section> }
export function RecentActivity() { return <section className="dashboard-card recent-empty" aria-labelledby="recent-title"><FileClock aria-hidden="true" /><div><h2 id="recent-title">No analyses yet</h2><p>Your completed market, business and financial analyses will appear here.</p></div></section> }
