import { useUi as useTextUi } from '../../i18n/uiContextValue'
import { LocalizedText } from '../../i18n/LocalizedText'
import { Accessibility, FileText, MapPin } from 'lucide-react'
import { Link } from 'react-router-dom'
import { useUi } from '../../i18n/uiContextValue'
import { Brand } from '../common/Brand'
export function Footer() {
  const { text: textUi } = useTextUi()
 const { language, setLanguage, t } = useUi(); return <footer className="footer"><div className="footer-accent" aria-hidden="true"><i /><i /><i /></div><div className="container footer-grid"><div><Brand inverse /><p>{t.footerText}</p><div className="footer-languages" aria-label={textUi("Languages")}>{([['en','English'],['hi','हिन्दी'],['mr','मराठी']] as const).map(([code,label]) => <button className={language === code ? 'active' : ''} onClick={() => setLanguage(code)} key={code}><LocalizedText value={label} /></button>)}</div></div><div><h3>{t.platform}</h3><Link to="/how-it-works">{t.nav[1]}</Link><Link to="/opportunities">{t.nav[2]}</Link><Link to="/market-analysis">{t.nav[3]}</Link></div><div><h3>{t.resources}</h3><Link to="/government-schemes">{t.nav[4]}</Link><Link to="/features"><LocalizedText value={"Services"} /></Link><Link to="/about">{t.nav[5]}</Link></div><div><h3>{t.important}</h3><Link to="/privacy"><LocalizedText value={"Privacy"} /></Link><Link to="/terms"><LocalizedText value={"Terms"} /></Link><Link to="/disclaimer"><LocalizedText value={"Accessibility & Disclaimer"} /></Link></div><div><h3>{t.support}</h3><span><Accessibility size={16} /><LocalizedText value={" Accessibility-first interface"} /></span><span><FileText size={16} /><LocalizedText value={" Prototype guidance only"} /></span><span><MapPin size={16} /><LocalizedText value={" India"} /></span></div></div><div className="container disclaimer"><LocalizedText value={t.disclaimer} /></div><div className="container copyright"><LocalizedText value={"© 2026 UdyamMitra · Smart India Hackathon prototype"} /></div></footer> }
