import { Circle, CircleMarker, MapContainer, Popup, TileLayer } from 'react-leaflet'
import type { MarketAnalysis } from '../../types/market'

const colors = { BUSINESS: '#e47a25', INSTITUTION: '#176b52', AMENITY: '#0c315c' }

export function MarketMap({ analysis }: { analysis: MarketAnalysis }) {
  const centre: [number, number] = [analysis.selectedLocation.latitude, analysis.selectedLocation.longitude]
  return <section className="market-map-card" aria-labelledby="market-map-title"><div className="market-section-heading"><div><span className="eyebrow">Spatial evidence</span><h2 id="market-map-title">Demonstration market map</h2></div><div className="map-legend" aria-label="Map legend"><span><i className="business" /> Businesses</span><span><i className="institution" /> Institutions</span><span><i className="amenity" /> Amenities</span></div></div><div className="market-map" role="img" aria-label={`Map of demonstration evidence within ${analysis.radiusKm} kilometres of ${analysis.selectedLocation.name}`}><MapContainer center={centre} zoom={analysis.radiusKm === 5 ? 12 : 11} scrollWheelZoom={false}><TileLayer attribution='&copy; OpenStreetMap contributors' url="https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png" /><Circle center={centre} radius={analysis.radiusKm * 1000} pathOptions={{ color: '#176b52', fillColor: '#176b52', fillOpacity: .07 }} /><CircleMarker center={centre} radius={9} pathOptions={{ color: '#082444', fillColor: '#fff', fillOpacity: 1 }}><Popup>Analysis centre: {analysis.selectedLocation.name}</Popup></CircleMarker>{analysis.mapPoints.map((point, index) => <CircleMarker key={`${point.kind}-${point.name}-${index}`} center={[point.latitude, point.longitude]} radius={6} pathOptions={{ color: colors[point.kind], fillColor: colors[point.kind], fillOpacity: .9 }}><Popup><strong>{point.name}</strong><br />{point.subtype.replaceAll('_', ' ')} · {point.distanceKm} km</Popup></CircleMarker>)}</MapContainer></div><details className="map-alternative"><summary>View map evidence as text</summary><ul>{analysis.mapPoints.map((point, index) => <li key={`${point.name}-${index}`}><strong>{point.name}</strong> — {point.kind.toLowerCase()}, {point.distanceKm} km</li>)}</ul></details></section>
}
