import { AlertCircle, BarChart3, Building2, LoaderCircle, MapPin, Route, Store } from 'lucide-react'
import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { Button } from '../../components/ui/Button'
import { getApiErrorMessage } from '../../services/apiError'
import { marketService } from '../../services/marketService'
import { profileService } from '../../services/profileService'
import type { MarketAnalysis, MarketLocationsResponse } from '../../types/market'
import type { EntrepreneurProfile } from '../../types/profile'
import { MarketMap } from './MarketMap'

const score = (value: number, label?: string) => <span className="market-score"><strong>{value}</strong>/100{label && <small>{label.replaceAll('_', ' ')}</small>}</span>

export function MarketAnalysisPage() {
  const [profile, setProfile] = useState<EntrepreneurProfile | null>(null); const [coverage, setCoverage] = useState<MarketLocationsResponse | null>(null); const [analysis, setAnalysis] = useState<MarketAnalysis | null>(null)
  const [radius, setRadius] = useState<5 | 10>(5); const [demoSlug, setDemoSlug] = useState(''); const [loading, setLoading] = useState(true); const [running, setRunning] = useState(false); const [error, setError] = useState('')
  useEffect(() => { void Promise.all([profileService.get(), marketService.locations(), marketService.latest()]).then(([savedProfile, locations, latest]) => { setProfile(savedProfile); setCoverage(locations); setAnalysis(latest); setDemoSlug(locations.resolvedLocationSlug ?? '') }).catch(reason => setError(getApiErrorMessage(reason, 'Unable to load market-analysis setup.'))).finally(() => setLoading(false)) }, [])
  const run = async () => { if (!coverage || (!coverage.resolvedLocationSlug && !demoSlug)) return; setRunning(true); setError(''); try { setAnalysis(await marketService.run(radius, coverage.resolvedLocationSlug ? undefined : demoSlug)) } catch (reason) { setError(getApiErrorMessage(reason, 'Unable to run market analysis.')) } finally { setRunning(false) } }
  if (loading) return <div className="market-page"><div className="market-loading"><LoaderCircle aria-hidden="true" /> Loading market coverage…</div></div>
  if (!profile || !coverage) return <div className="market-page"><div className="market-error" role="alert"><AlertCircle /><h1>Market analysis is unavailable</h1><p>{error || 'Complete your entrepreneur profile and try again.'}</p></div></div>
  const supported = coverage.resolutionStatus === 'resolved_demo_location'
  return <div className="market-page"><header className="market-heading"><span className="eyebrow">Curated demonstration evidence</span><h1>Hyper-Local Market Analysis</h1><p>Evaluate competition, market reach, demand signals and local business conditions within your selected area.</p><div className="market-disclaimer"><AlertCircle aria-hidden="true" /><p>{coverage.disclaimer}</p></div></header>
    <section className="market-controls" aria-labelledby="analysis-location-title"><div><h2 id="analysis-location-title">Profile location</h2><dl><div><dt>Village</dt><dd>{profile.village || 'Not provided'}</dd></div><div><dt>Taluka / Block</dt><dd>{profile.taluka || 'Not provided'}</dd></div><div><dt>District</dt><dd>{profile.district || 'Not provided'}</dd></div><div><dt>State</dt><dd>{profile.state || 'Not provided'}</dd></div></dl><p className={supported ? 'coverage-status supported' : 'coverage-status'}>{supported ? 'Prototype market coverage available' : 'Detailed prototype market evidence is currently available for selected demonstration locations.'}</p></div><div className="analysis-options"><fieldset><legend>Analysis radius</legend>{([5, 10] as const).map(value => <label key={value}><input type="radio" name="radius" checked={radius === value} onChange={() => setRadius(value)} /> <span>{value} km</span></label>)}</fieldset>{!supported && <label className="demo-location-select"><span>Demo analysis location</span><select value={demoSlug} onChange={event => setDemoSlug(event.target.value)}><option value="">Select a demonstration location</option>{coverage.locations.map(location => <option value={location.slug} key={location.id}>{location.name}, {location.district}</option>)}</select><small>This does not change your profile location.</small></label>}<Button type="button" onClick={() => void run()} disabled={running || (!supported && !demoSlug)}>{running ? <><LoaderCircle className="spin" /> Analysing…</> : 'Run Market Analysis'}</Button></div></section>{error && <div className="market-error-inline" role="alert">{error}</div>}
    {analysis && <MarketResults analysis={analysis} />}
  </div>
}

function MarketResults({ analysis }: { analysis: MarketAnalysis }) {
  const summaryCards = [[Store, 'Demo businesses', analysis.summary.businessPointsConsidered], [Building2, 'Institutions', analysis.summary.institutionsConsidered], [Route, 'Amenities', analysis.summary.amenitiesConsidered], [MapPin, 'Selected radius', `${analysis.radiusKm} km`]] as const
  return <div className="market-results"><section className="market-summary" aria-labelledby="market-summary-title"><div className="market-section-heading"><div><span className="eyebrow">Analysis snapshot</span><h2 id="market-summary-title">Market summary</h2><p>{analysis.selectedLocation.name} · {new Date(analysis.createdAt).toLocaleString('en-IN')}</p></div><span className="demo-pill">DEMONSTRATION DATA</span></div><div className="market-stat-grid">{summaryCards.map(([Icon, label, value]) => <article key={label}><Icon aria-hidden="true" /><span><small>{label}</small><strong>{value}</strong></span></article>)}</div><div className="signal-groups"><article><h3>Lower competition</h3><p>{analysis.summary.lowerCompetitionCategories.join(', ')}</p></article><article><h3>Higher demand</h3><p>{analysis.summary.higherDemandCategories.join(', ')}</p></article><article><h3>Strong market access</h3><p>{analysis.summary.strongMarketAccessCategories.join(', ')}</p></article></div></section><MarketMap analysis={analysis} /><section className="market-business-section" aria-labelledby="business-evidence-title"><div className="market-section-heading"><div><span className="eyebrow">All supported categories</span><h2 id="business-evidence-title">Business market evidence</h2><p>Signals describe local market conditions only; they are not personalized recommendations.</p></div><BarChart3 aria-hidden="true" /></div><div className="market-table-wrap"><table><thead><tr><th>Business</th><th>Demand</th><th>Competition</th><th>Competitors ({analysis.radiusKm} km)</th><th>Nearest</th><th>Reach</th><th>Access</th><th>Supply chain</th><th>Evidence</th></tr></thead><tbody>{analysis.businesses.map(business => <tr key={business.businessId}><th scope="row">{business.businessName}</th><td>{score(business.demandScore, business.demandLabel)}</td><td>{score(business.competitionIntensity, business.competitionLabel)}</td><td>{business.competitorsWithinSelectedRadius}</td><td>{business.nearestCompetitorKm == null ? 'None within 10 km' : `${business.nearestCompetitorKm} km`}</td><td>{score(business.marketReachScore)}</td><td>{score(business.marketAccessScore)}</td><td>{score(business.supplyChainScore)}</td><td><details className="market-evidence"><summary>View Evidence</summary><Evidence business={business} /></details></td></tr>)}</tbody></table></div></section><section className="market-continue"><div><span className="eyebrow">Next step</span><h2>Continue to Business Feasibility</h2><p>Use this saved snapshot to evaluate all supported opportunities against your profile.</p></div><Link className="button button--success" to="/opportunities">Continue to Business Feasibility</Link></section></div>
}

function Evidence({ business }: { business: MarketAnalysis['businesses'][number] }) { return <div className="evidence-panel"><h3>{business.businessName}</h3><div className="evidence-score-grid"><span>Demand {score(business.demandScore, business.demandLabel)}</span><span>Market reach {score(business.marketReachScore)}</span><span>Market access {score(business.marketAccessScore)}</span><span>Supply chain {score(business.supplyChainScore)}</span><span>Market opportunity signal {score(business.marketOpportunitySignal)}</span></div><section><h4>Competition breakdown</h4><ul><li>0–2 km: {business.competitors02Km}</li><li>&gt;2–5 km: {business.competitors25Km}</li><li>&gt;5–10 km: {business.competitors510Km}</li><li>Nearest competitor: {business.nearestCompetitorKm == null ? 'none within 10 km' : `${business.nearestCompetitorKm} km`}</li><li>Competition intensity: {business.competitionIntensity}/100 ({business.competitionLabel.replaceAll('_', ' ')})</li></ul></section><section><h4>Distribution channels</h4>{business.distributionChannels.length ? <ul>{business.distributionChannels.map(channel => <li key={`${channel.type}-${channel.name}`}>{channel.name} ({channel.type.replaceAll('_', ' ')}) — {channel.distanceKm} km</li>)}</ul> : <p>No mapped channel within the selected radius.</p>}</section><section><h4>Localized threats</h4>{business.localizedThreats.length ? <ul>{business.localizedThreats.map(threat => <li key={threat.code}><strong>{threat.code.replaceAll('_', ' ')}:</strong> {threat.explanation}</li>)}</ul> : <p>No rule-based threat triggered by this demonstration evidence.</p>}</section><section><h4>Evidence and reasons</h4><ul>{business.evidence.map(item => <li key={item}>{item}</li>)}</ul></section><section><h4>Nearby matching competitors</h4>{business.nearbyCompetitors.length ? <ul>{business.nearbyCompetitors.map((competitor, index) => <li key={`${competitor.name}-${index}`}>{competitor.name} — {competitor.distanceKm} km</li>)}</ul> : <p>No matching demonstration competitor within 10 km.</p>}</section></div> }
