"""create business profiles

Revision ID: 1261ac4e3bd3
Revises: a4215e901568
Create Date: 2026-09-03 00:10:57.357501
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '1261ac4e3bd3'
down_revision: Union[str, None] = 'a4215e901568'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('business_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.Enum('RETAIL', 'SERVICES', 'AGRICULTURE', 'FOOD_PROCESSING', 'MANUFACTURING', name='business_category', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('short_description', sa.String(length=320), nullable=False),
    sa.Column('detailed_description', sa.Text(), nullable=False),
    sa.Column('business_type', sa.Enum('SERVICE', 'RETAIL', 'AGRI_ALLIED', 'PROCESSING', 'RENTAL', name='business_type', native_enum=False, create_constraint=True), nullable=False),
    sa.Column('minimum_capital', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('maximum_capital', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_setup_cost_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_setup_cost_max', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('working_capital_min', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('working_capital_max', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('required_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('preferred_skills', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('optional_resources', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('equipment', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('customer_segments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('market_drivers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('competition_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('supply_chain_factors', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('major_risks', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('required_registrations', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('operating_requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_business_profiles_business_type'), 'business_profiles', ['business_type'], unique=False)
    op.create_index(op.f('ix_business_profiles_category'), 'business_profiles', ['category'], unique=False)
    op.create_index(op.f('ix_business_profiles_is_active'), 'business_profiles', ['is_active'], unique=False)
    op.create_index(op.f('ix_business_profiles_name'), 'business_profiles', ['name'], unique=False)
    op.create_index(op.f('ix_business_profiles_slug'), 'business_profiles', ['slug'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_business_profiles_slug'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_name'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_is_active'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_category'), table_name='business_profiles')
    op.drop_index(op.f('ix_business_profiles_business_type'), table_name='business_profiles')
    op.drop_table('business_profiles')
    # ### end Alembic commands ###
