"""create entrepreneur profiles

Revision ID: a4215e901568
Revises: 20260902_01
Create Date: 2026-09-02 23:53:53.275124
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'a4215e901568'
down_revision: Union[str, None] = '20260902_01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrepreneur_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('age_group', sa.Enum('AGE_18_25', 'AGE_26_35', 'AGE_36_45', 'AGE_46_60', 'AGE_60_PLUS', name='age_group', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('education', sa.Enum('NO_FORMAL', 'UP_TO_10TH', 'TWELFTH', 'ITI_VOCATIONAL', 'DIPLOMA', 'GRADUATE', 'POSTGRADUATE', 'OTHER', name='education_level', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('previous_experience', sa.Enum('NONE', 'LESS_THAN_1_YEAR', 'ONE_TO_THREE_YEARS', 'THREE_TO_FIVE_YEARS', 'FIVE_PLUS_YEARS', name='experience_level', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('district', sa.String(length=100), nullable=True),
    sa.Column('taluka', sa.String(length=100), nullable=True),
    sa.Column('village', sa.String(length=120), nullable=True),
    sa.Column('pincode', sa.String(length=6), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('capital_range', sa.Enum('UP_TO_50000', '50000_TO_100000', '100000_TO_250000', '250000_TO_500000', '500000_TO_1000000', 'ABOVE_1000000', name='capital_range', native_enum=False, create_constraint=True), nullable=True),
    sa.Column('own_capital', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('loan_required', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('has_existing_business', sa.Boolean(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_step', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entrepreneur_profiles_user_id'), 'entrepreneur_profiles', ['user_id'], unique=True)
    op.create_table('entrepreneur_resources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('other_description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['entrepreneur_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'name', name='uq_entrepreneur_resource')
    )
    op.create_index(op.f('ix_entrepreneur_resources_profile_id'), 'entrepreneur_resources', ['profile_id'], unique=False)
    op.create_table('entrepreneur_skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('profile_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('other_description', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['entrepreneur_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'name', name='uq_entrepreneur_skill')
    )
    op.create_index(op.f('ix_entrepreneur_skills_profile_id'), 'entrepreneur_skills', ['profile_id'], unique=False)
    op.create_table('existing_businesses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entrepreneur_profile_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=160), nullable=False),
    sa.Column('business_category', sa.String(length=120), nullable=False),
    sa.Column('years_operating', sa.Integer(), nullable=False),
    sa.Column('initial_investment', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_revenue', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('monthly_expenses', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('employee_count', sa.Integer(), nullable=False),
    sa.Column('estimated_monthly_customers', sa.Integer(), nullable=False),
    sa.Column('major_challenges', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['entrepreneur_profile_id'], ['entrepreneur_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_existing_businesses_entrepreneur_profile_id'), 'existing_businesses', ['entrepreneur_profile_id'], unique=True)
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_existing_businesses_entrepreneur_profile_id'), table_name='existing_businesses')
    op.drop_table('existing_businesses')
    op.drop_index(op.f('ix_entrepreneur_skills_profile_id'), table_name='entrepreneur_skills')
    op.drop_table('entrepreneur_skills')
    op.drop_index(op.f('ix_entrepreneur_resources_profile_id'), table_name='entrepreneur_resources')
    op.drop_table('entrepreneur_resources')
    op.drop_index(op.f('ix_entrepreneur_profiles_user_id'), table_name='entrepreneur_profiles')
    op.drop_table('entrepreneur_profiles')
    # ### end Alembic commands ###
