import { ArrowRight, BriefcaseBusiness, Calculator, CheckCircle2, FileCheck2, FileText, Languages, Landmark, MapPin, MessageSquareText, Route, Search, ShieldCheck, Store, UserRound } from 'lucide-react'
import { Link } from 'react-router-dom'
import { ButtonLink } from '../../components/ui/Button'
import { useUi } from '../../i18n/uiContextValue'

const serviceIcons = [MapPin, BriefcaseBusiness, Calculator, Landmark, FileCheck2, MessageSquareText]
const serviceLinks = ['/market-analysis', '/opportunities', '/financial-plan/preview', '/schemes', '/documents', '/advisor']
const stageIcons = [UserRound, MapPin, Search, BriefcaseBusiness, Calculator, FileText]
const businesses = ['Tailoring & Alteration', 'Mobile Repair', 'Kirana Store', 'Dairy Enterprise', 'Poultry Enterprise', 'Flour Mill', 'Food Processing', 'Agricultural Equipment Rental']
function Heading({ eyebrow, title, text }: { eyebrow: string; title: string; text?: string }) { return <div className="gov-section-heading"><span>{eyebrow}</span><h2>{title}</h2>{text && <p>{text}</p>}</div> }

export function HomePage() { const { t } = useUi(); return <>
  <section className="gov-hero"><div className="container gov-hero-grid"><div className="gov-hero-copy"><span className="institutional-eyebrow"><i />{t.eyebrow}</span><h1>{t.heroTitle}</h1><p>{t.heroText}</p><div className="hero-actions"><ButtonLink to="/register">{t.start}<ArrowRight /></ButtonLink><ButtonLink to="/opportunities" variant="outline">{t.explore}</ButtonLink></div><small><ShieldCheck /> SIH public-service prototype · Transparent, evidence-led guidance</small></div><aside className="decision-journey" aria-label={t.journeyTitle}><header><span><Route /></span><div><small>UDYAMMITRA SERVICE JOURNEY</small><h2>{t.journeyTitle}</h2></div></header><ol>{t.journey.map((item, index) => <li key={item}><span>{String(index + 1).padStart(2, '0')}</span><strong>{item}</strong></li>)}</ol></aside></div></section>
  <section className="public-update"><div className="container"><strong>{t.update}</strong><p>{t.updateText}</p><Link to="/market-analysis">{t.learn}<ArrowRight /></Link></div></section>
  <section className="gov-section"><div className="container"><Heading eyebrow="PUBLIC DIGITAL SERVICES" title={t.servicesTitle} text={t.servicesText} /><div className="service-grid">{t.services.map((name, index) => { const Icon = serviceIcons[index]; return <Link className="service-card" to={serviceLinks[index]} key={name}><span><Icon /></span><h3>{name}</h3><p>{index === 0 ? t.marketText : index === 1 ? t.opportunitiesText : index === 2 ? t.financeText : 'Clear, structured guidance designed for rural entrepreneurs.'}</p><small>{t.learn}<ArrowRight /></small></Link> })}</div></div></section>
  <section className="gov-section gov-section-muted" id="how-it-works"><div className="container"><Heading eyebrow="SIX-STEP PROCESS" title={t.howTitle} text={t.howText} /><ol className="gov-process">{t.stages.map((name, index) => { const Icon = stageIcons[index]; return <li key={name}><span><Icon /></span><small>{String(index + 1).padStart(2, '0')}</small><strong>{name}</strong></li> })}</ol></div></section>
  <section className="gov-section"><div className="container"><Heading eyebrow="WHY LOCAL EVIDENCE MATTERS" title={t.evidenceTitle} /><div className="evidence-challenges">{t.evidence.map((name, index) => <article key={name}><span>{String(index + 1).padStart(2, '0')}</span><h3>{name}</h3><p>{t.evidenceText[index]}</p></article>)}</div></div></section>
  <section className="gov-section market-feature"><div className="container feature-split"><div><Heading eyebrow="HYPER-LOCAL INTELLIGENCE" title={t.marketTitle} text={t.marketText} /><ul className="formal-checks">{t.marketItems.map(item => <li key={item}><CheckCircle2 />{item}</li>)}</ul><ButtonLink to="/market-analysis">{t.marketCta}<ArrowRight /></ButtonLink></div><aside className="evidence-document"><header><MapPin /><div><small>LOCAL MARKET EVIDENCE</small><strong>Village / Taluka / District</strong></div></header><div className="radius-band"><span>5 km</span><i /><span>10 km</span></div><dl><div><dt>Competition overview</dt><dd>Distance-based evidence</dd></div><div><dt>Demand indicators</dt><dd>Rule-based signals</dd></div><div><dt>Market access</dt><dd>Mapped amenities</dd></div><div><dt>Localized risks</dt><dd>Structured reasons</dd></div></dl><p>{t.notice}</p></aside></div></section>
  <section className="gov-section gov-section-muted"><div className="container"><div className="section-action"><Heading eyebrow="BUSINESS KNOWLEDGE CATALOG" title={t.opportunitiesTitle} text={t.opportunitiesText} /><ButtonLink to="/opportunities" variant="outline">{t.explore}<ArrowRight /></ButtonLink></div><div className="public-business-grid">{businesses.map((name, index) => <Link to="/opportunities" key={name}><span><Store /></span><div><small>BUSINESS PROFILE {String(index + 1).padStart(2, '0')}</small><h3>{name}</h3></div><ArrowRight /></Link>)}</div></div></section>
  <section className="gov-section"><div className="container future-grid"><article><Calculator /><Heading eyebrow="UPCOMING SERVICE" title={t.financeTitle} text={t.financeText} /><div className="module-status">{t.coming}</div></article><article><Landmark /><Heading eyebrow="VERIFICATION-LED GUIDANCE" title={t.schemeTitle} text={t.schemeText} /><ButtonLink to="/schemes" variant="outline">{t.nav[4]}<ArrowRight /></ButtonLink></article></div></section>
  <section className="language-promotion"><div className="container"><Languages /><div><Heading eyebrow="MULTILINGUAL ACCESS" title={t.languagesTitle} text={t.languagesText} /><div className="language-names"><span>English</span><span>हिन्दी</span><span>मराठी</span></div></div></div></section>
  <section className="gov-section transparency"><div className="container"><Heading eyebrow="RESPONSIBLE DESIGN" title={t.trustTitle} /><div className="trust-list">{t.trust.map(item => <span key={item}><ShieldCheck />{item}</span>)}</div><div className="prototype-notice"><strong>{t.noticeTitle}</strong><p>{t.notice}</p></div></div></section>
  <section className="gov-final-cta"><div className="container"><div><span>BEGIN YOUR ENTERPRISE JOURNEY</span><h2>{t.finalTitle}</h2><p>{t.finalText}</p></div><div><ButtonLink to="/register">{t.getStarted}<ArrowRight /></ButtonLink><ButtonLink to="/opportunities" variant="secondary">{t.explore}</ButtonLink></div></div></section>
  </> }
